server:
  name: go-rest-api
  port: 8080

provider: mongo
sql:
  driver: mysql
  data_source_name: root:abcd1234@/masterdata?charset=utf8&parseTime=True&loc=Local
mongo:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: masterdata

log:
  level: info
  map:
    time: "@timestamp"
    msg: message
middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size

status:
  not_found: 0
  duplicate_key: 0
  success: 1
  version_error: 2
  validation_error: 4
  error: 4
